[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "https://favorite-fonts-aleksey-vl-ivanov.netlify.app/*"
  to = "https://favorite-fonts.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://favorite-fonts-aleksey-vl-ivanov.netlify.app/*"
  to = "https://favorite-fonts.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://favorite-fonts.aleksey-vl-ivanov.com/*"
  to = "https://favorite-fonts.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true
